site_name: Vortex Odometry Motion Template
site_description: A customizable, powerful odometry and motion control template for VEX V5 PROS.
site_author: Jonah Chang

theme:
  name: material
  logo: logo.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: green
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green

nav:
  - Home: index.md
  - API Reference:
    - Odom: odom.md
    - Chassis: chassis.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jonahchang207/Vortex
