site_name: Vortex Odometry Motion Template
site_description: A customizable, powerful odometry and motion control template for VEX V5 PROS.
site_author: Jonah Chang

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: green
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green

nav:
  - Home: index.md
  - API Reference:
    - Odom: odom.md
    - Chassis: chassis.md
